### ISSUE TITLE
Firefox 85 ignore userChrome and userContent

### ISSUE THREAD

**Issue by xLinkOut** [Pepitortue/FirefoxCSS-Safari-theme#1]
I'm using Firefox 85 on macOS Big Sur 11.2, and both userChrome and userContent are ignored. I've found that enabling `toolkit.legacyUserProfileCustomizations.stylesheets` (that is _false_ by default) in `about:config` solve the issue. I suggest adding this information in the readme. 

[Source.](https://bugzilla.mozilla.org/show_bug.cgi?id=1661742)

**Comment by Pepitortue** [comment]
Hi,

The installation process was updated to correct this issue.
Thanks for the heads up.
