### ISSUE TITLE
Library is broken in Firefox 85

### ISSUE THREAD

**Issue by xLinkOut** [Pepitortue/FirefoxCSS-Safari-theme#2]
Library panel is broken in Firefox 85 on macOS Big Sur 11.2. There is a lot of unused space covering the history, bookmarks and download list entries. I am attaching a screenshot.

<img width="364" alt="Schermata 2021-02-13 alle 20 34 09" src="https://user-images.githubusercontent.com/14892153/107859652-10dd5a80-6e3b-11eb-8041-74db4d7f6db7.png">

**Comment by Pepitortue** [comment]
Hi,

The latest update fixed this issue, I'm not more customizing this panel.
Please note that this is a complete theme change to match with the latest Safari 15 update one-liner theme.
